# Use the Jenkins base image
FROM jenkins/jenkins:lts

# Switch to root user to make system changes
USER root

# Install Docker CLI
RUN apt-get update && apt-get install -y \
    docker.io

# Add the docker group if it does not exist and add the jenkins user to it
RUN getent group docker || groupadd docker && \
    usermod -aG docker jenkins

# Switch back to jenkins user
USER jenkins

# Expose the Jenkins port
EXPOSE 8080

